"""initial schema

Revision ID: 291d58a7baf9
Revises: 
Create Date: 2026-09-10 21:09:22.777280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.models

# revision identifiers, used by Alembic.
revision: str = '291d58a7baf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_codes',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('device_id', sa.String(length=17), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by_owner_id', app.core.models.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_codes_code'), 'activation_codes', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('owners',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('user_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('devices',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('owner_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('agent_id', app.core.models.GUID(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=17), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('board', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('owner_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('device_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_device_id'), 'conversations', ['device_id'], unique=False)
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('owner_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('conversation_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('latency_ms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_owner_id'), 'messages', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_owner_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_device_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('owners')
    op.drop_table('users')
    op.drop_index(op.f('ix_activation_codes_code'), table_name='activation_codes')
    op.drop_table('activation_codes')
    # ### end Alembic commands ###
