"""add agent, provider_cred tables

Revision ID: 757689c4a3a7
Revises: 291d58a7baf9
Create Date: 2026-09-10 21:58:28.526696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.models

# revision identifiers, used by Alembic.
revision: str = '757689c4a3a7'
down_revision: Union[str, Sequence[str], None] = '291d58a7baf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('owner_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('tts_provider', sa.String(length=64), nullable=False),
    sa.Column('tts_voice', sa.String(length=64), nullable=False),
    sa.Column('emotion_level', sa.String(length=32), nullable=False),
    sa.Column('tools_enabled', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('chat_log_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('provider_creds',
    sa.Column('id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('owner_id', app.core.models.GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('secret_last4', sa.String(length=8), nullable=False),
    sa.Column('fallback_of', app.core.models.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fallback_of'], ['provider_creds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_creds_owner_id'), 'provider_creds', ['owner_id'], unique=False)
    op.add_column('conversations', sa.Column('agent_id', app.core.models.GUID(length=36), nullable=True))
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'agent_id')
    op.drop_index(op.f('ix_provider_creds_owner_id'), table_name='provider_creds')
    op.drop_table('provider_creds')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
